//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.SQLDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacebookCategory
    {
        public int Id { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> VideoCategoryId { get; set; }
    
        public virtual VideoCategory VideoCategory { get; set; }
    }
}
