//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.SQLDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPreferences
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int YoutubeCategoryId { get; set; }
        public decimal Score { get; set; }
    
        public virtual User User { get; set; }
        public virtual VideoCategory VideoCategory { get; set; }
    }
}
